spring.application.name=SiteConstrutor

# Configuração do Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true


# Libera todos os endpoints 
management.endpoints.web.exposure.include=health,info,metrics
# Para mostrar detalhes da saúde (como conexão com banco de dados)
management.endpoint.health.show-details=when_authorized


# Obrigatório: Chave com pelo menos 32 caracteres
jwt.secret-key=${JWT_SECRET_KEY}
# Opcional: Tempo de expiração (padrão 24h)
jwt.expiration-time=${JWT_EXPIRATION_TIME}
# Opcional: Caminhos que NÃO precisam de token
jwt.excluded-paths=/auth/login, /public/**, /swagger-ui/**, /v3/api-docs/**, /swagger-ui.html
#login e senha unica
auth.admin.user=${USERNAME_LOGIN}
auth.admin.password=${PASSWORD_LOGIN}