spring.application.name=SiteConstrutor

# Mostra o SQL formatado no console (ajuda muito no desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Atualiza o banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update